[project]
name = "hinomaru-home-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-cotton>=1.5.2",
    "django-tailwind-cli>=2.21.1",
    "faker>=34.0.2",
    "wagtail>=6.3.2",
]
